// Send branded confirm/reject email to the vet (Resend) + sync the booking row
// to the clinic Google Sheet ledger. No Interakt / WhatsApp automation —
// WhatsApp is click-to-chat only on the user side.
import { createClient } from "https://esm.sh/@supabase/supabase-js@2.45.0";

const corsHeaders = {
  "Access-Control-Allow-Origin": "*",
  "Access-Control-Allow-Headers":
    "authorization, x-client-info, apikey, content-type",
};

const SITE_BASE = "https://petosauras.com";

async function sendEmail(
  apiKey: string,
  to: string,
  subject: string,
  html: string,
): Promise<{ ok: boolean; status: number; body: any }> {
  const res = await fetch("https://api.resend.com/emails", {
    method: "POST",
    headers: {
      Authorization: `Bearer ${apiKey}`,
      "Content-Type": "application/json",
    },
    body: JSON.stringify({
      from: "Petosauras <noreply@petosauras.com>",
      to,
      subject,
      html,
    }),
  });
  let body: any = null;
  try {
    body = await res.json();
  } catch {
    body = await res.text().catch(() => null);
  }
  return { ok: res.ok, status: res.status, body };
}

function buildEmailHtml(opts: {
  bookingRef: string;
  vetName: string;
  petName: string;
  petType: string;
  ownerName: string;
  slotDate: string;
  slotTime: string;
  reason: string;
  symptoms: string[];
  isEmergency: boolean;
  confirmLink: string;
  rejectLink: string;
  rescheduleLink: string;
  whatsappLink: string | null;
}) {
  const symptomsBlock = opts.symptoms.length
    ? `<p style="margin:6px 0;color:#555"><b>Symptoms:</b> ${opts.symptoms.join(", ")}</p>`
    : "";
  const emergencyBlock = opts.isEmergency
    ? `<div style="display:inline-block;background:#FFF4E5;color:#B45309;border:1px solid #FCD9A8;padding:6px 12px;border-radius:999px;font-size:12px;font-weight:700;margin:8px 0">⚡ EMERGENCY — Priority Appointment</div>`
    : "";
  const waBlock = opts.whatsappLink
    ? `<p style="margin:18px 0 0;font-size:13px;color:#555">Quick chat: <a href="${opts.whatsappLink}" style="color:#25D366;font-weight:700">Open WhatsApp</a></p>`
    : "";

  return `<!doctype html><html><body style="margin:0;padding:0;background:#FEFAF5;font-family:-apple-system,Segoe UI,Roboto,sans-serif;color:#1a1a1a">
  <table role="presentation" width="100%" cellpadding="0" cellspacing="0" style="background:#FEFAF5;padding:24px 0">
    <tr><td align="center">
      <table role="presentation" width="560" cellpadding="0" cellspacing="0" style="background:#fff;border-radius:18px;overflow:hidden;box-shadow:0 4px 20px rgba(0,0,0,0.05)">
        <tr><td style="background:#E8633A;padding:18px 24px;color:#fff;font-weight:700;font-size:18px">🐾 Petosauras</td></tr>
        <tr><td style="padding:24px">
          <h1 style="margin:0 0 6px;font-size:20px">New Booking Request</h1>
          <p style="margin:0 0 14px;color:#666;font-size:13px">Booking Ref: <b>${opts.bookingRef}</b></p>
          ${emergencyBlock}
          <table role="presentation" width="100%" cellpadding="0" cellspacing="0" style="background:#FAF6EE;border-radius:12px;padding:14px;margin:8px 0 18px">
            <tr><td style="font-size:14px;line-height:1.7">
              <b>Pet:</b> ${opts.petName} (${opts.petType})<br/>
              <b>Owner:</b> ${opts.ownerName}<br/>
              <b>Date:</b> ${opts.slotDate}<br/>
              <b>Time:</b> ${opts.slotTime}<br/>
              <b>Reason:</b> ${opts.reason}
            </td></tr>
          </table>
          ${symptomsBlock}
          <div style="text-align:center;margin:22px 0 8px">
            <a href="${opts.confirmLink}" style="display:inline-block;background:#16A34A;color:#fff;text-decoration:none;padding:12px 22px;border-radius:999px;font-weight:700;font-size:14px;margin:6px 4px">✅ Confirm Appointment</a>
            <a href="${opts.rejectLink}" style="display:inline-block;background:#DC2626;color:#fff;text-decoration:none;padding:12px 22px;border-radius:999px;font-weight:700;font-size:14px;margin:6px 4px">❌ Reject Appointment</a>
          </div>
          <p style="text-align:center;margin:8px 0 0"><a href="${opts.rescheduleLink}" style="color:#E8633A;font-size:13px;font-weight:600">Reschedule / Open Vet Dashboard</a></p>
          ${waBlock}
          <hr style="border:none;border-top:1px solid #eee;margin:24px 0" />
          <p style="font-size:12px;color:#888;margin:0;text-align:center">This booking was generated by Petosauras.</p>
        </td></tr>
      </table>
    </td></tr>
  </table>
  </body></html>`;
}

Deno.serve(async (req) => {
  if (req.method === "OPTIONS") {
    return new Response("ok", { headers: corsHeaders });
  }

  try {
    const { booking_id } = await req.json();
    if (!booking_id) {
      return new Response(JSON.stringify({ error: "booking_id required" }), {
        status: 400,
        headers: { ...corsHeaders, "Content-Type": "application/json" },
      });
    }

    const supabase = createClient(
      Deno.env.get("SUPABASE_URL")!,
      Deno.env.get("SUPABASE_SERVICE_ROLE_KEY")!,
    );

    const { data: booking, error: bErr } = await supabase
      .from("vet_bookings")
      .select(
        "id, booking_reference, reason_for_visit, symptoms, is_emergency, vet_id, user_id, pet_id, slot_id, action_token, status",
      )
      .eq("id", booking_id)
      .single();
    if (bErr || !booking) throw new Error(bErr?.message ?? "booking missing");

    const [{ data: vet }, { data: pet }, { data: owner }, { data: slot }] =
      await Promise.all([
        supabase
          .from("vets")
          .select(
            "id, full_name, email, whatsapp_number, phone, clinic_name, clinic_address",
          )
          .eq("id", booking.vet_id)
          .single(),
        booking.pet_id
          ? supabase
              .from("pets")
              .select("name, species, pet_type")
              .eq("id", booking.pet_id)
              .single()
          : Promise.resolve({ data: null as any }),
        supabase
          .from("profiles")
          .select("full_name")
          .eq("id", booking.user_id)
          .single(),
        supabase
          .from("vet_slots")
          .select("slot_date, start_time")
          .eq("id", booking.slot_id)
          .single(),
      ]);

    if (!vet) throw new Error("vet missing");

    const tokenQ = `booking_id=${booking.id}&token=${booking.action_token}`;
    const confirmLink = `${SITE_BASE}/vet-booking-action?${tokenQ}&action=confirm`;
    const rejectLink = `${SITE_BASE}/vet-booking-action?${tokenQ}&action=reject`;
    const rescheduleLink = `${SITE_BASE}/vet-dashboard?booking_id=${booking.id}&action=reschedule`;

    const rawPhone = (vet.whatsapp_number || vet.phone || "").replace(
      /[^\d]/g,
      "",
    );
    const waPhone = rawPhone.startsWith("91") ? rawPhone : `91${rawPhone}`;
    const waMessage =
      `Hello Dr. ${vet.full_name}, regarding Petosauras booking ${booking.booking_reference}.`;
    const whatsappLink =
      rawPhone.length >= 10
        ? `https://wa.me/${waPhone}?text=${encodeURIComponent(waMessage)}`
        : null;

    const slotTime = String(slot?.start_time ?? "").slice(0, 5);
    const subject = `New Petosauras Booking · ${booking.booking_reference}`;
    const html = buildEmailHtml({
      bookingRef: booking.booking_reference,
      vetName: vet.full_name,
      petName: pet?.name ?? "—",
      petType: pet?.species ?? pet?.pet_type ?? "—",
      ownerName: owner?.full_name ?? "Pet parent",
      slotDate: slot?.slot_date ?? "",
      slotTime,
      reason: booking.reason_for_visit ?? "Consultation",
      symptoms: booking.symptoms ?? [],
      isEmergency: !!booking.is_emergency,
      confirmLink,
      rejectLink,
      rescheduleLink,
      whatsappLink,
    });

    // Send email
    const apiKey = Deno.env.get("RESEND_API_KEY");
    let emailRes: { ok: boolean; status: number; body: any } = {
      ok: false,
      status: 0,
      body: { error: "missing_recipient_or_key" },
    };
    if (vet.email && apiKey) {
      try {
        emailRes = await sendEmail(apiKey, vet.email, subject, html);
      } catch (e: any) {
        emailRes = { ok: false, status: 0, body: { error: e?.message } };
      }
    }

    const nowIso = new Date().toISOString();
    await supabase.from("vet_notifications").insert({
      vet_id: vet.id,
      booking_id: booking.id,
      channel: "email",
      recipient: vet.email ?? "",
      subject,
      message: `New booking ${booking.booking_reference} for ${pet?.name ?? "pet"}`,
      payload: { html, confirmLink, rejectLink, rescheduleLink, whatsappLink },
      provider_response: { status: emailRes.status, body: emailRes.body },
      status: emailRes.ok ? "sent" : "failed",
      attempts: 1,
      max_attempts: 5,
      last_attempt_at: nowIso,
      delivered_at: emailRes.ok ? nowIso : null,
      last_error: emailRes.ok ? null : `HTTP ${emailRes.status}`,
    });

    // In-app notification for the user
    await supabase.from("notifications").insert({
      user_id: booking.user_id,
      type: "booking",
      title: "Booking request sent to vet",
      body: "Your booking request has been sent. The vet will confirm or reject it shortly.",
      is_read: false,
    });

    // Google Sheet ledger sync — best effort, never fails the booking
    const sheetUrl = Deno.env.get("GOOGLE_SHEET_LEDGER_WEBHOOK_URL");
    let sheetOk = false;
    let sheetError: string | null = null;
    const sheetPayload = {
      booking_reference: booking.booking_reference,
      vet_name: vet.full_name,
      clinic_name: vet.clinic_name ?? "",
      vet_email: vet.email ?? "",
      vet_phone: vet.phone ?? vet.whatsapp_number ?? "",
      pet_name: pet?.name ?? "",
      pet_type: pet?.species ?? pet?.pet_type ?? "",
      owner_name: owner?.full_name ?? "",
      slot_date: slot?.slot_date ?? "",
      slot_time: slotTime,
      reason: booking.reason_for_visit ?? "",
      status: booking.status,
      confirm_link: confirmLink,
      reject_link: rejectLink,
      whatsapp_link: whatsappLink,
    };
    if (sheetUrl) {
      try {
        const sheetRes = await fetch(sheetUrl, {
          method: "POST",
          headers: { "Content-Type": "application/json" },
          body: JSON.stringify(sheetPayload),
        });
        sheetOk = sheetRes.ok;
        if (!sheetRes.ok) sheetError = `HTTP ${sheetRes.status}`;
      } catch (e: any) {
        sheetError = e?.message ?? "fetch_failed";
      }
    } else {
      sheetError = "missing_GOOGLE_SHEET_LEDGER_WEBHOOK_URL";
    }

    if (sheetOk) {
      await supabase
        .from("vet_bookings")
        .update({ google_sheet_synced: true })
        .eq("id", booking.id);
    }
    await supabase.from("vet_ledger_sync_logs").insert({
      booking_id: booking.id,
      status: sheetOk ? "success" : "error",
      error: sheetError,
      payload: sheetPayload,
    });

    return new Response(
      JSON.stringify({
        ok: true,
        email: { ok: emailRes.ok, status: emailRes.status },
        sheet: { ok: sheetOk, error: sheetError },
      }),
      { headers: { ...corsHeaders, "Content-Type": "application/json" } },
    );
  } catch (e: any) {
    return new Response(JSON.stringify({ error: e.message }), {
      status: 500,
      headers: { ...corsHeaders, "Content-Type": "application/json" },
    });
  }
});
