// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://plyonactsujycdmyskou.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InBseW9uYWN0c3VqeWNkbXlza291Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzU1NzIwNzQsImV4cCI6MjA5MTE0ODA3NH0.99jjRcNU53gUw1r8VBRFnrhz3IyxQ2DqF9F8qb_qX24";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});